src/Entity/Announce.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @ORM\Entity(repositoryClass="App\Repository\AnnounceRepository")
 * @Vich\Uploadable
 */
class Announce
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeUlm", inversedBy="typeUlm")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Marque;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $vitesseMax;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbrHvol;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $yearUlm;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $parachute;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $transponder;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $enabled;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Model;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\State", inversedBy="stateUlm")
     * @ORM\JoinColumn(nullable=false)
     */
    private $state;
    /**
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="picture", size="imageSize")
     * @Assert\File(
     * maxSize="2000k",
     * maxSizeMessage="Le fichier excède 2000Ko.",
     * mimeTypes={"image/png", "image/jpeg", "image/jpg", "image/svg+xml", "image/gif"},
     * mimeTypesMessage= "formats autorisés: png, jpeg, jpg, svg, gif"
     * )
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable = true)
     *
     * @var string
     */
    private $picture;

    /**
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="picture2", size="imageSize")
     * @Assert\File(
     * maxSize="2000k",
     * maxSizeMessage="Le fichier excède 2000Ko.",
     * mimeTypes={"image/png", "image/jpeg", "image/jpg", "image/svg+xml", "image/gif"},
     * mimeTypesMessage= "formats autorisés: png, jpeg, jpg, svg, gif"
     * )
     *
     * @var File
     */
    private $imageFile2;

    /**
     * @ORM\Column(type="string", length=255, nullable = true)
     *
     * @var string
     */
    private $picture2;

    /**
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="picture3", size="imageSize")
     * @Assert\File(
     * maxSize="2000k",
     * maxSizeMessage="Le fichier excède 2000Ko.",
     * mimeTypes={"image/png", "image/jpeg", "image/jpg", "image/svg+xml", "image/gif"},
     * mimeTypesMessage= "formats autorisés: png, jpeg, jpg, svg, gif"
     * )
     *
     * @var File
     */
    private $imageFile3;

    /**
     * @ORM\Column(type="string", length=255, nullable = true)
     *
     * @var string
     */
    private $picture3;

    /**
     * @return string
     */
    public function getPicture3(): ?string
    {
        return $this->picture3;
    }

    /**
     * @param string $picture3
     * @return Announce
     */
    public function setPicture3(?string $picture3): Announce
    {
        $this->picture3 = $picture3;
        return $this;
    }

    /**
     * @ORM\Column(type="datetime", nullable = true)
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $Price;

    /**
     * @ORM\Column(type="date")
     */
    private $DatePost;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="Announce")
     */
    private $announce;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="announces")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Region", inversedBy="announce")
     */
    private $region;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Favorite", mappedBy="Announce")
     */
    private $favorites;

    public function __construct()
    {
        $this->announce = new ArrayCollection();
        $this->favorites = new ArrayCollection();
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setImageFile(?File $image = null)
    {
        $this->imageFile = $image;
        if (null !== $image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setImageFile2(?File $image = null)
    {
        $this->imageFile2 = $image;
        if (null !== $image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile2(): ?File
    {
        return $this->imageFile2;
    }

    public function setPicture($imageName)
    {
        $this->picture = $imageName;
    }

    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setImageFile3(?File $image = null)
    {
        $this->imageFile3 = $image;
        if (null !== $image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile3(): ?File
    {
        return $this->imageFile3;
    }


    public function setImageSize($imageSize)
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getType(): ?TypeUlm
    {
        return $this->Type;
    }

    public function setType(?TypeUlm $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->Marque;
    }

    public function setMarque(string $Marque): self
    {
        $this->Marque = $Marque;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->Model;
    }

    public function setModel(string $Model): self
    {
        $this->Model = $Model;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getState(): ?State
    {
        return $this->state;
    }

    public function setState(?State $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getDatePost(): ?\DateTimeInterface
    {
        return $this->DatePost;
    }

    public function setDatePost(\DateTimeInterface $DatePost): self
    {
        $this->DatePost = $DatePost;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getAnnounce(): Collection
    {
        return $this->announce;
    }

    public function addAnnounce(Comment $announce): self
    {
        if (!$this->announce->contains($announce)) {
            $this->announce[] = $announce;
            $announce->setAnnounce($this);
        }

        return $this;
    }

    public function removeAnnounce(Comment $announce): self
    {
        if ($this->announce->contains($announce)) {
            $this->announce->removeElement($announce);
            // set the owning side to null (unless already changed)
            if ($announce->getAnnounce() === $this) {
                $announce->setAnnounce(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPicture2(): ?string
    {
        return $this->picture2;
    }

    public function setPicture2(?string $picture2): self
    {
        $this->picture2 = $picture2;

        return $this;
    }


    public function getParachute(): ?bool
    {
        return $this->parachute;
    }

    public function setParachute(?bool $parachute): self
    {
        $this->parachute = $parachute;

        return $this;
    }

    public function getTransponder(): ?bool
    {
        return $this->transponder;
    }

    public function setTransponder(?bool $transponder): self

src/Controller/AnnounceController.php
<?php

namespace App\Controller;

use App\Entity\Announce;
use App\Entity\Favorite;
use App\Entity\Region;
use App\Entity\TypeUlm;
use App\Form\AnnounceType;
use App\Form\RegionType;
use App\Form\SearchPriceType;
use App\Form\SearchType;
use App\Repository\AnnounceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/announces")
 */
class AnnounceController extends Controller
{
    /**
     * @Route("/pendulaires", name="announce_pendulaires", methods="GET|POST")
     */
    public function index(AnnounceRepository $announceRepository, Request $request): Response
    {
        $formSearch = $this->createForm(SearchType::class);
        $formSearch->handleRequest($request);
        $formRegion = $this->createForm(RegionType::class);
        $formRegion->handleRequest($request);
        $em = $this->getDoctrine()->getManager();

        $dataRegion = $formRegion->getData();
        $region = $dataRegion['filter'];
        if ($formRegion->isSubmitted() && $region != null) {
            $announces = $em->getRepository(Announce::class)->findByRegionField($region->getName());
        } else {
            $pendulaires = $em->getRepository(TypeUlm::class)->findBy(['Type' => 'Pendulaires']);
            $announces = $em->getRepository(Announce::class)->findBy(['Type' => $pendulaires, 'enabled' => 1], ['DatePost' => 'DESC ']);
        }

        $dataSearch = $formSearch->getData();
        $modelSearch = $dataSearch['search'];
        if ($formSearch->isSubmitted() && $formSearch->isValid()) {
            $announces = $em->getRepository(Announce::class)->findAnnouncementsByModel($modelSearch);
        }

        $paginator = $this->get('knp_paginator');
        $result = $paginator->paginate(
            $announces,
            $request->query->getInt('page', 1),
            $request->query->getInt('limit', 9)
        );

        return $this->render(
            'announce/pendulaires/index.html.twig',
            [
                'announces' => $result,
                'modelSearch' => $modelSearch,
                'region' => $region,
                'formSearch' => $formSearch->createView(),
                'formRegion' => $formRegion->createView(),
            ]
        );
    }

    /**
     * @Route("/new", name="announce_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $announce = new Announce();
        $form = $this->createForm(AnnounceType::class, $announce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $announce->setUser($this->getUser());
            $announce->setEnabled(1);
            $announce->setDatePost(new \DateTime('NOW'));
            $em->persist($announce);
            $em->flush();

            return $this->redirectToRoute('announce_pendulaires');
        }

        return $this->render('user/new.html.twig', [
            'announce' => $announce,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="announce_show", methods="GET")
     */
    public function show(Announce $announce): Response
    {
        $em = $this->getDoctrine()->getManager();
        $favorite = $em->getRepository(Favorite::class)->findAll();
        return $this->render('announce/pendulaires/show.html.twig', ['announce' => $announce, 'favorite' => $favorite]);
    }

    /**
     * @Route("/{id}/edit", name="announce_edit", methods="GET|POST")
     */
    public function edit(Request $request, Announce $announce): Response
    {
        if ($this->getUser() !== $announce->getUser()) {
            $this->addFlash(
                'comment',
                'Impossible de supprimer ce message.'
            );
            return $this->redirectToRoute('announce_pendulaires');
        }
        $form = $this->createForm(AnnounceType::class, $announce);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('announce_edit', ['id' => $announce->getId()]);
        }

        return $this->render('announce/edit.html.twig', [
            'announce' => $announce,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}", name="announce_delete", methods="DELETE")
     */
    public function delete(Request $request, Announce $announce): Response
    {
        if ($this->getUser() !== $announce->getUser()) {
            $this->addFlash(
                'comment',
                'Impossible de supprimer ce message.'
            );
            return $this->redirectToRoute('profile');
        }
        if ($this->isCsrfTokenValid('delete'.$announce->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $announce->setEnabled(0);
            $em->flush();
        }

        return $this->redirectToRoute('profile');
    }
}

templates/announce/pendulaires/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="container pt-5">
        <h5 class="card-title col-7 mt-5"> Annonces Ulm pendulaire</h5>

        <hr>
        <div class="row">
            <div class="col-8 ml-5 mt-3">
                {{ form_start(formSearch) }}
                {{ form_row(formSearch.search) }}
            </div>
            <div class="col-2 mt-3">
                {{ form_row(formSearch.Rechercher) }}
                {{ form_end(formSearch) }}
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-2 mt-1">
                <div class="btn btn-primary pr-5 pl-5 btn-sm"><i
                            class="fas fa-sort"></i> {{ knp_pagination_sortable(announces, 'Trier par prix','Price') }}
                </div>
            </div>
            <div class="col-2 mt-1">
                <div class="btn btn-primary pr-5 pl-5 btn-sm"><i
                            class="fas fa-sort"></i> {{ knp_pagination_sortable(announces, 'Trier par date','Price') }}
                </div>
            </div>
            <div class="col-3 mt-1">
                {{ form_start(formRegion,{'attr':{'onChange':'submit()' }}) }}
                {{ form_row(formRegion.filter) }}
                {{ form_end(formRegion) }}
            </div>
        </div>

        <hr class="mb-4">
        <ul class="cards mt-3">
            {% for announce in announces %}
                <li class="cards_item ">
                    <div class="card">
                        <a class="card_image" href="{{ path('announce_show', {'id': announce.id}) }}">
                            <img src="{{ asset('images/products/' ~ announce.picture) }}" class=" img-announce">
                        </a>
                        <div class="card_content">
                            <h5 class="card-title"> {{ announce.model }} - {{ announce.price }}€</h5>
                            <h6 class="card-title">{{ announce.city }}</h6>
                            <p>Posté le: {{ announce.DatePost.date|date("d/m/Y") }}</p>
                            <div class="card-footer w-100 text-center">
                                <a href="{{ path('announce_show', {'id': announce.id}) }}"
                                   class="text-dark col-2 font-weight-bold" title="Voir">
                                    <i class="fas fa-eye text-warning pr-1 mr-1"></i>Voir l'annonce</a>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <div class="navigation d-flex justify-content-center">
            {{ knp_pagination_render(announces) }}
        </div>
    </div>
{% endblock %}

templates/announce/pendulaires/show.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                {% if announce.picture2 is not null %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                {% endif %}
                {% if announce.picture3 is not null %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                {% endif %}
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="img-responsive w-100 text-center"
                         src="{{ asset('images/products/' ~ announce.picture) }}"
                         alt="{{ announce.picture }}"></div>
                {% if announce.picture2 is not null %}
                    <div class="carousel-item">
                        <img class="img-responsive w-100 text-center"
                             src="{{ asset('images/products/' ~ announce.picture2) }}"
                             alt="{{ announce.picture }}">
                    </div>
                {% else %}
                {% endif %}
                {% if announce.picture3 is not null %}
                    <div class="carousel-item">
                        <img class="img-responsive w-100 text-center"
                             src="{{ asset('images/products/' ~ announce.picture3) }}"
                             alt="{{ announce.picture }}">
                    </div>
                {% endif %}
            </div>
            {% if announce.picture2 is not null %}
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            {% endif %}
        </div>

        <hr>
        <h5 class="card-title text-center">{{ announce.marque }} - {{ announce.model }} - {{ announce.price }}€</h5>
        <hr>
        <p><strong> {{ announce.state.state }}</strong> / Post|é le: {{ announce.DatePost.date|date("m/d/Y") }};</p>
        <p>
            <strong> Parachute: </strong>{% if announce.parachute == 1 %} Oui {% else %} Non {% endif %}
            <strong class="ml-3"> |
                Transpondeur: </strong>{% if announce.transponder == 1 %} Oui {% else %} Non {% endif %}
            <strong class="ml-3"> | Heures de
                vols: </strong>{% if announce.nbrHvol is defined %} {{ announce.nbrHvol }} heures{% else %} Non renseigées. {% endif %}
            <strong class="ml-3"> | Année
                de
                construction: </strong>{% if announce.yearUlm is defined %} {{ announce.yearUlm }} {% else %} Non renseigné. {% endif %}
            <strong class="ml-3">| Vitesse
                maxi: </strong>{% if announce.vitesseMax %} {{ announce.vitesseMax }} km/h {% else %} Non renseignées. {% endif %}

        </p>
        <p class="mb-5 text-justify"><strong>Description:</strong> {{ announce.description|raw }}</p>
        <div class="pb-5">
            <a href="{{ path('announce_pendulaires') }}" class="btn btn-dark float-left">
                <i class="fas fa-chevron-left"></i> Retour aux annonces</a>
            {% if app.user is not null %}
                <a href="{{ path('contact', {'id': announce.id}) }}" class="btn btn-primary float-right"><i
                            class="far fa-envelope"></i>
                    Contacter le vendeur</a>
                {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                    {% set thisAnnounce = 0 %}
                    {% set idFavorite = "" %}
                    {% for favorite in favorite %}
                        {% if favorite.announce.id == announce.id %}
                            {% if favorite.active == 1 %}
                                {% set thisAnnounce = 1 %}
                                {% set idFavorite = favorite.id %}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    {% if thisAnnounce == 0 %}
                        <a href="{{ path('favorite_new', { 'id': announce.id } ) }}"
                           class="btn btn-primary float-right ml-2" id="msg_anchor">
                            <i class="far fa-heart"></i> Ajouter dans mes favoris</a>
                    {% else %}
                        <a href="{{ path('favorite_defav', { 'id': idFavorite } ) }}"
                           class="btn btn-primary float-right ml-2" id="msg_anchor">
                            <i class="fas fa-heart text-warning"></i> Supprimer des favoris </a>
                    {% endif %}
                {% endif %}
            {% else %}
                <a href="{{ path('security_login') }}" class="btn btn-primary float-right">
                    <i class="far fa-address-card"></i>
                    Connectez vous pour contacter le vendeur</a>
            {% endif %}

        </div>
    </div>
{% endblock %}